[
  "Freddie Mercury",
  "Lata Mangeshkar",
  "Michael Jackson",
  "Kishore Kumar",
  "Taylor Swift",
  "Mohammed Rafi",
  "Arijit Singh",
  "Adele",
  "Asha Bhosle",
  "Elvis Presley",
  "Shreya Ghoshal",
  "David Bowie",
  "Mukesh",
  "Beyoncé",
  "Sonu Nigam",
  "Frank Sinatra",
  "Udit Narayan",
  "Billie Eilish",
  "Kumar Sanu",
  "Prince",
  "Alka Yagnik",
  "Paul McCartney",
  "KK",
  "Aretha Franklin",
  "Sunidhi Chauhan",
  "John Lennon",
  "Mohit Chauhan",
  "Whitney Houston",
  "Shaan",
  "Bob Dylan",
  "Manna Dey",
  "Stevie Wonder",
  "Hemanta Mukherjee",
  "Rihanna",
  "Geeta Dutt",
  "The Weeknd",
  "Kavita Krishnamurthy",
  "Drake",
  "S. P. Balasubrahmanyam",
  "Lady Gaga",
  "Jagjit Singh",
  "Ed Sheeran",
  "Chitra Singh",
  "Justin Bieber",
  "Pankaj Udhas",
  "Ariana Grande",
  "Talat Mahmood",
  "Bruno Mars",
  "K. S. Chithra",
  "Dua Lipa",
  "Zubeen Garg",
  "Harry Styles",
  "Lucky Ali",
  "Sia",
  "Kailash Kher",
  "Katy Perry",
  "Shankar Mahadevan",
  "Lana Del Rey",
  "Himesh Reshammiya",
  "SZA",
  "Rahat Fateh Ali Khan",
  "Post Malone",
  "Atif Aslam",
  "Nusrat Fateh Ali Khan",
  "Olivia Rodrigo",
  "Adnan Sami",
  "Shawn Mendes",
  "Badshah",
  "Camila Cabello",
  "Neha Kakkar",
  "Selena Gomez",
  "Armaan Malik",
  "Doja Cat",
  "Amaal Mallik",
  "Kendrick Lamar",
  "Jubin Nautiyal",
  "Sam Smith",
  "Palak Muchhal",
  "Eminem",
  "Pritam",
  "Halsey",
  "Amit Trivedi",
  "Tyler, The Creator",
  "Vishal Dadlani",
  "Kali Uchis",
  "Shekhar Ravjiani",
  "Lorde",
  "Anuv Jain",
  "Phoebe Bridgers",
  "Prateek Kuhad",
  "Mitski",
  "Ritviz",
  "Hozier",
  "The Local Train",
  "Sufjan Stevens",
  "When Chai Met Toast",
  "Bon Iver",
  "Parekh & Singh",
  "FKA Twigs",
  "Yellow Diary",
  "James Blake",
  "Sajjan Raj Vaidya",
  "Mac DeMarco",
  "Sushant KC",
  "Alex G",
  "Narayan Gopal",
  "Clairo",
  "Aruna Lama",
  "Tame Impala",
  "Tara Devi",
  "Joji",
  "Prem Dhoj Pradhan",
  "Daniel Caesar",
  "Fatteman",
  "Beabadoobee",
  "Deepak Kharel",
  "Girl in Red",
  "Nabin K Bhattarai",
  "Rex Orange County",
  "Sugam Pokharel",
  "Conan Gray",
  "Adrian Pradhan",
  "Wallows",
  "Bipul Chettri",
  "Cavetown",
  "Amrit Gurung",
  "Glass Animals",
  "Bartika Eam Rai",
  "Khruangbin",
  "Vipul Goyal",
  "Cigarettes After Sex",
  "Anupam Roy",
  "Arctic Monkeys",
  "Rupam Islam",
  "The Neighborhood",
  "Nachiketa Chakraborty",
  "Radiohead",
  "Sahana Bajpaie",
  "The Strokes",
  "Arnob",
  "Beach House",
  "Somlata Acharyya",
  "Men I Trust",
  "Srikanto Acharya",
  "Still Woozy",
  "Lopamudra Mitra",
  "Unknown Mortal Orchestra",
  "Runa Laila",
  "Thundercat",
  "Sabina Yasmin",
  "James (Nagar Baul)",
  "Steve Lacy",
  "Ayub Bachchu",
  "Frank Ocean",
  "Andrew Kishore",
  "Blood Orange",
  "Kanak Chapa",
  "Arlo Parks",
  "Subir Nandi",
  "Moses Sumney",
  "Mitali Mukherjee",
  "Japanese Breakfast",
  "Kalyani Singh",
  "Weyes Blood",
  "Bhupen Hazarika",
  "Sharon Van Etten",
  "Usha Uthup",
  "Angel Olsen",
  "Remo Fernandes",
  "Lucy Dacus",
  "Alisha Chinai",
  "Julien Baker",
  "Baba Sehgal",
  "Indigo De Souza",
  "Palash Sen",
  "The Japanese House",
  "Silk Route",
  "Soccer Mommy",
  "Indian Ocean",
  "Big Thief",
  "Parikrama",
  "Alvvays",
  "Strings",
  "Wolf Alice",
  "Junoon",
  "alt-J",
  "Vital Signs",
  "CHVRCHES",
  "Noori",
  "London Grammar",
  "Ali Azmat",
  "Tamino",
  "Hadiqa Kiani",
  "Jacob Collier",
  "Zeb Bangash",
  "Madison Beer",
  "Meesha Shafi",
  "Sabrina Carpenter",
  "Ali Sethi",
  "Tate McRae",
  "Abida Parveen",
  "Gracie Abrams",
  "Shubha Mudgal",
  "PinkPantheress",
  "Papon",
  "Benny Dayal",
  "Sid Sriram",
  "Jonita Gandhi",
  "Shashwat Singh",
  "Antara Mitra",
  "Amit Kumar",
  "Anuradha Paudwal",
  "Suresh Wadkar",
  "Kavita Paudwal",
  "Sadhana Sargam",
  "Abhijeet Bhattacharya",
  "Vinod Rathod",
  "Jaspinder Narula",
  "Richa Sharma",
  "Madushree",
  "Clinton Cerejo",
  "Vijay Prakash",
  "Rekha Bhardwaj",
  "Master Saleem",
  "Mamta Sharma",
  "Aditi Singh Sharma",
  "Shilpa Rao",
  "Neeti Mohan",
  "Bhoomi Trivedi",
  "Jasleen Royal",
  "Shalmali Kholgade",
  "Amanat Ali",
  "Shafqat Amanat Ali",
  "Ali Zafar",
  "Farhan Saeed",
  "Asim Azhar",
  "Momina Mustehsan",
  "Quratulain Balouch",
  "Aima Baig",
  "Sahir Ali Bagga",
  "Nabeel Shaukat Ali",
  "Zoe Viccaji",
  "Zulfiqar Jabbar Khan",
  "Xulfi",
  "Rohail Hyatt",
  "Sherjan Ahmad",
  "Abdullah Siddiqui",
  "Hasan Raheem",
  "Abdul Hannan",
  "Kaifi Khalil",
  "Taha G",
  "Maanu",
  "Natasha Noorani",
  "Shubh",
  "AP Dhillon",
  "Gurinder Gill",
  "Sidhu Moose Wala",
  "Karan Aujla",
  "Diljit Dosanjh",
  "Amrit Maan",
  "Sharry Maan",
  "Gippy Grewal",
  "Babbu Maan",
  "Satinder Sartaaj",
  "Amrinder Gill",
  "Kulwinder Billa",
  "Jassie Gill",
  "Hardy Sandhu",
  "Ninja",
  "Mankirt Aulakh",
  "Parmish Verma",
  "Jordan Sandhu",
  "Gurnam Bhullar",
  "Snehdeep Singh Kalsi",
  "The PropheC",
  "Tarsame Singh Saini",
  "Taz Stereo Nation",
  "Apache Indian",
  "Bally Sagoo",
  "Panjabi MC",
  "Jay Sean",
  "Rishi Rich",
  "Juggy D",
  "Raghav",
  "Dr Zeus",
  "Zack Knight",
  "Mickey Singh",
  "Arjun",
  "Vidya Vox",
  "Shirley Setia",
  "Penn Masala",
  "Chai Town",
  "The Yellow Diary",
  "Peter Cat Recording Co.",
  "Lifafa",
  "Begum",
  "Taba Chake",
  "Dream Note",
  "Naalayak",
  "Osho Jain",
  "Aditya Rikhari",
  "Kushagra",
  "Saaheal",
  "Asees Kaur",
  "Nikhita Gandhi",
  "Abhay Jodhpurkar",
  "Ankit Tiwari",
  "Arko",
  "Mithoon",
  "Tanishk Bagchi",
  "Raftaar",
  "Divine",
  "Emiway Bantai",
  "Kr$na",
  "Seedhe Maut",
  "Prabh Deep",
  "Naezy",
  "MC Stan",
  "Munawar Faruqui",
  "Srushti Tawade",
  "Paradox",
  "MC Square",
  "Fotty Seven",
  "Bali",
  "Shah Rule",
  "D'Evil",
  "Gravity",
  "Deep Kalsi",
  "Karma",
  "Yashraj",
  "Chaahat Khanna",
  "Mintu Haryanvi",
  "Gulzaar Chhaniwala",
  "MD Desi Rocker",
  "Bintu Pabra",
  "Masoom Sharma",
  "Ruchika Jangid",
  "Renuka Panwar",
  "Aman Jaji",
  "Pranjal Dahiya",
  "Kay Pee",
  "Hina Khan",
  "Vipul Goyal",
  "Phosphenes",
  "The Edge Band",
  "Cobweb",
  "Robin Tamang",
  "Abhaya Subba",
  "Albatross",
  "The Shadows Nepal",
  "Monkey Temple",
  "Underside",
  "Jindabaad",
  "Night",
  "Kutumba",
  "Amber Gurung",
  "Gopal Yonjan",
  "Amber Gurung",
  "Bhakta Raj Acharya",
  "Om Bikram Bista",
  "Karna Das",
  "Phiroj Shyangden",
  "Milan Newar",
  "Shiva Pariyar",
  "Rajesh Payal Rai",
  "Swarup Raj Acharya",
  "Yama Buddha",
  "Uniq Poet",
  "Vten",
  "Sacar",
  "Dong",
  "Laure",
  "Ashish Rana",
  "Kaveesh Jha",
  "Trishala Gurung",
  "Wangden Sherpa",
  "Yugal Gurung",
  "Oasis Thapa",
  "Rupam Islam",
  "Kabir Suman",
  "Anjan Dutt",
  "Shyamal Mitra",
  "Satinath Mukhopadhyay",
  "Sandhya Mukhopadhyay",
  "Arati Mukhopadhyay",
  "Pratima Bandopadhyay",
  "Hoimanti Shukla",
  "Indranil Sen",
  "Silajit Majumder",
  "Rupankar Bagchi",
  "Iman Chakraborty",
  "Lagnajita Chakraborty",
  "Anirudh Ravichander",
  "Sid Sriram",
  "Chinmayi Sripada",
  "Jonny Greenwood",
  "Thom Yorke",
  "George Ezra",
  "Lewis Capaldi",
  "James Arthur",
  "Calum Scott",
  "Tom Odell",
  "George Michael",
  "Annie Lennox",
  "Phil Collins",
  "Sting",
  "Peter Gabriel",
  "Kate Bush",
  "Liam Gallagher",
  "Noel Gallagher",
  "Richard Ashcroft",
  "Damon Albarn",
  "Jarvis Cocker",
  "Morrissey",
  "Johnny Marr",
  "Ian Curtis",
  "Robert Smith",
  "Siouxsie Sioux",
  "Elizabeth Fraser",
  "Sinead O'Connor",
  "Dolores O'Riordan",
  "Enya",
  "Björk",
  "Sigur Rós",
  "Aurora",
  "Sigrid",
  "MØ",
  "Lykke Li",
  "Robyn",
  "Tove Lo",
  "Zedd",
  "Avicii",
  "Kygo",
  "Alan Walker",
  "Calvin Harris",
  "David Guetta",
  "Tiësto",
  "Marshmello",
  "Martin Garrix",
  "Skrillex",
  "Diplo",
  "Fred again..",
  "Four Tet",
  "Jamie xx",
  "Burial",
  "Aphex Twin",
  "Flying Lotus",
  "Kamasi Washington",
  "Jon Batiste",
  "Gregory Porter",
  "Norah Jones",
  "Diana Krall",
  "Michael Bublé",
  "Amy Winehouse",
  "Joss Stone",
  "Duffy",
  "Paloma Faith",
  "Emeli Sandé",
  "Jess Glynne",
  "Rita Ora",
  "Ellie Goulding",
  "Charli XCX",
  "FKA Twigs",
  "Rina Sawayama",
  "PinkPantheress",
  "Shygirl",
  "Eartheater",
  "Caroline Polachek",
  "Weyes Blood",
  "Angel Olsen",
  "Sharon Van Etten",
  "Mitski",
  "Japanese Breakfast",
  "Lucy Dacus",
  "Julien Baker",
  "Phoebe Bridgers",
  "Clairo",
  "Beabadoobee",
  "Arlo Parks",
  "Girl in Red",
  "King Princess",
  "MUNA",
  "The Japanese House",
  "Soccer Mommy",
  "Snail Mail",
  "Jay-Z",
  "Nas",
  "The Notorious B.I.G.",
  "Tupac Shakur",
  "Snoop Dogg",
  "Dr. Dre",
  "Ice Cube",
  "Eazy-E",
  "Rakim",
  "Big Daddy Kane",
  "Andre 3000",
  "Big Boi",
  "Lauryn Hill",
  "Missy Elliott",
  "Queen Latifah",
  "Lil Wayne",
  "Kanye West",
  "Kendrick Lamar",
  "J. Cole",
  "Travis Scott",
  "Future",
  "Young Thug",
  "Lil Uzi Vert",
  "Playboi Carti",
  "21 Savage",
  "Megan Thee Stallion",
  "Cardi B",
  "Nicki Minaj",
  "Ice Spice",
  "GloRilla",
  "Central Cee",
  "Dave",
  "Stormzy",
  "Skepta",
  "Little Simz",
  "Loyle Carner",
  "Arlo Parks",
  "Joy Crookes",
  "Celeste",
  "Mahalia",
  "Jorja Smith",
  "Kali Uchis",
  "SZA",
  "Summer Walker",
  "Kehlani",
  "Jhené Aiko",
  "Teyana Taylor",
  "H.E.R.",
  "Victoria Monét",
  "Coco Jones",
  "Brent Faiyaz",
  "Giveon",
  "Lucky Daye",
  "SiR",
  "Daniel Caesar",
  "Steve Lacy",
  "Omar Apollo",
  "Frank Ocean",
  "Miguel",
  "Solange",
  "Janelle Monáe",
  "Erykah Badu",
  "Jill Scott",
  "D'Angelo",
  "Maxwell",
  "Sade",
  "Seal",
  "Lenny Kravitz",
  "Ben Harper",
  "Jack Johnson",
  "Jason Mraz",
  "John Mayer",
  "James Bay",
  "Vance Joy",
  "Hozier",
  "George Ezra",
  "Rag'n'Bone Man",
  "Sam Fender",
  "Holly Humberstone",
  "Griff",
  "Cat Burns",
  "Flowerovlove",
  "Laufey",
  "Eloise",
  "Bruno Major",
  "Jacob Collier",
  "Madison Beer",
  "Sabrina Carpenter",
  "Tate McRae",
  "Gracie Abrams",
  "Renee Rapp",
  "Nessa Barrett",
  "Mimi Webb",
  "Lauren Spencer Smith",
  "Gayle",
  "Benson Boone",
  "Stephen Sanchez",
  "Teddy Swims",
  "Noah Kahan",
  "Zach Bryan",
  "Tyler Childers",
  "Kacey Musgraves",
  "Chris Stapleton",
  "Luke Combs",
  "Morgan Wallen",
  "Lainey Wilson",
  "Maren Morris",
  "Miranda Lambert",
  "Carrie Underwood",
  "Kelly Clarkson",
  "P!nk",
  "Avril Lavigne",
  "Hayley Williams",
  "Amy Lee",
  "Florence Welch",
  "Marina Diamandis",
  "Lana Del Rey",
  "Lorde",
  "Sky Ferreira",
  "Halsey",
  "Troye Sivan",
  "Lauv",
  "Jeremy Zucker",
  "Conan Gray",
  "Wallows",
  "The 1975",
  "Arctic Monkeys",
  "Tame Impala",
  "Glass Animals",
  "Foster The People",
  "Cage The Elephant",
  "The Black Keys",
  "The White Stripes",
  "The Killers",
  "Kings of Leon",
  "Imagine Dragons",
  "OneRepublic",
  "Coldplay",
  "Snow Patrol",
  "The Script",
  "Bastille",
  "The Lumineers",
  "Mumford & Sons",
  "Of Monsters and Men",
  "Fleet Foxes",
  "Bon Iver",
  "Sufjan Stevens",
  "Iron & Wine",
  "Elliott Smith",
  "Nick Drake",
  "Jeff Buckley",
  "Father John Misty",
  "Mac DeMarco",
  "Thundercat",
  "Flying Lotus",
  "Kamasi Washington",
  "Robert Glasper",
  "Esperanza Spalding",
  "Yussef Dayes",
  "Tom Misch",
  "Jordan Rakei",
  "Moonchild",
  "Hiatus Kaiyote",
  "Khruangbin",
  "Texas",
  "The Cardigans",
  "The Cranberries",
  "The Corrs",
  "Enya",
  "Sinead O'Connor",
  "Van Morrison",
  "U2",
  "The Pogues",
  "Thin Lizzy",
  "Rory Gallagher",
  "Chet Baker",
  "Billie Holiday",
  "Ella Fitzgerald",
  "Nina Simone",
  "Nat King Cole",
  "Sam Cooke",
  "Otis Redding",
  "Ray Charles",
  "Marvin Gaye",
  "Al Green",
  "Bill Withers",
  "Curtis Mayfield",
  "Isaac Hayes",
  "Barry White",
  "Luther Vandross",
  "George Benson",
  "Lionel Richie",
  "Chaka Khan",
  "Donna Summer",
  "Gloria Gaynor",
  "Diana Ross",
  "Tina Turner",
  "Cher",
  "Barbra Streisand",
  "Bette Midler",
  "Dolly Parton",
  "Kenny Rogers",
  "Willie Nelson",
  "Johnny Cash",
  "Waylon Jennings",
  "Kris Kristofferson",
  "Townes Van Zandt",
  "Lucinda Williams",
  "Emmylou Harris",
  "Gram Parsons",
  "Grateful Dead",
  "Phish",
  "Dave Matthews",
  "John Butler",
  "Xavier Rudd",
  "Ziggy Marley",
  "Damian Marley",
  "Stephen Marley",
  "Buju Banton",
  "Sizzla",
  "Beenie Man",
  "Sean Paul",
  "Shaggy",
  "Koffee",
  "Chronixx",
  "Protoje",
  "Lila Iké",
  "Tyla",
  "Ayra Starr",
  "Burna Boy",
  "Wizkid",
  "Davido",
  "Tems",
  "Olamide",
  "Asake",
  "Fireboy DML",
  "Rema",
  "Ckay",
  "Joeboy",
  "Tiwa Savage",
  "Santi",
  "Amaarae",
  "Odunsi",
  "Lady Donli",
  "Sautisol",
  "Black Coffee",
  "Master KG",
  "Niniola",
  "Fela Kuti",
  "Tony Allen",
  "Miriam Makeba",
  "Hugh Masekela",
  "Brenda Fassie",
  "Ali Farka Touré",
  "Oumou Sangaré",
  "Salif Keita",
  "Angelique Kidjo",
  "Youssou N'Dour",
  "Baaba Maal",
  "Tinariwen",
  "Abhijeet Sawant",
  "Amit Sana",
  "Rahul Vaidya",
  "Prajakta Shukre",
  "Aditi Singh Sharma",
  "Anusha Mani",
  "Shruti Pathak",
  "Alyssa Mendonsa",
  "Caralisa Monteiro",
  "Dominique Cerejo",
  "Sanjeevani",
  "Jaspinder Narula",
  "Richa Sharma",
  "Harshdeep Kaur",
  "Akriti Kakar",
  "Sukriti Kakar",
  "Prakriti Kakar",
  "Niti Mohan",
  "Shakti Mohan",
  "Mukti Mohan",
  "Meiyang Chang",
  "Monali Thakur",
  "Mamta Sharma",
  "Bhoomi Trivedi",
  "Aditi Paul",
  "Nandini Srikar",
  "Apeksha Dandekar",
  "Shibani Dandekar",
  "Anushka Manchanda",
  "Saba Azad",
  "Monica Dogra",
  "Suman Sridhar",
  "Kavita Seth",
  "Rekha Bhardwaj",
  "Usha Uthup",
  "Runa Laila",
  "Usha Mangeshkar",
  "Meena Mangeshkar",
  "Hridaynath Mangeshkar",
  "Suresh Wadkar",
  "Hariharan",
  "Pankaj Udhas",
  "Anup Jalota",
  "Talat Aziz",
  "Bhupinder Singh",
  "Mitali Singh",
  "Sudesh Bhosale",
  "Vinod Rathod",
  "Jolly Mukherjee",
  "Bali Brahmbhatt",
  "Sukhwinder Singh",
  "Kailash Kher",
  "Tochi Raina",
  "Mohan Kanan",
  "Kshitij Tarey",
  "Zubeen Garg",
  "Angaraag Mahanta",
  "Papon",
  "Kalpana Patowary",
  "Zubeen Garg",
  "Siddharth Mahadevan",
  "Shivam Mahadevan",
  "Armaan Malik",
  "Amaal Mallik",
  "Yash Narvekar",
  "Tanishk Bagchi",
  "Sachet Tandon",
  "Parampara Thakur",
  "Akhil Sachdeva",
  "B Praak",
  "Jaani",
  "Millind Gaba",
  "Guru Randhawa",
  "Jassie Gill",
  "Hardy Sandhu",
  "Ammy Virk",
  "Sidhu Moose Wala",
  "Karan Aujla",
  "Diljit Dosanjh",
  "Nimrat Khaira",
  "Sunanda Sharma",
  "Jasmine Sandlas",
  "Nooran Sisters",
  "Jyoti Nooran",
  "Sultana Nooran",
  "Master Saleem",
  "Lakhwinder Wadali",
  "Satinder Sartaaj",
  "Gurdas Maan",
  "Babbu Maan",
  "Harbhajan Mann",
  "Amrinder Gill",
  "Kulwinder Billa",
  "Shivjot",
  "Gurnam Bhullar",
  "Jordan Sandhu",
  "Mankirt Aulakh",
  "Parmish Verma",
  "Sharry Maan",
  "Gippy Grewal",
  "Bappi Lahiri",
  "Anu Malik",
  "Alisha Chinai",
  "Sharon Prabhakar",
  "Baba Sehgal",
  "Lucky Ali",
  "Raageshwari",
  "Anaida",
  "Mehnaz",
  "Suneeta Rao",
  "Sagarika",
  "Shaan",
  "KK",
  "Euphoria",
  "Silk Route",
  "Mohit Chauhan",
  "Zubeen Garg",
  "Lucky Ali",
  "Remo Fernandes",
  "Usha Uthup",
  "Ila Arun",
  "Shubha Mudgal",
  "Suresh Wadkar",
  "Hariharan",
  "Kavita Krishnamurthy",
  "Alka Yagnik",
  "Kumar Sanu",
  "Udit Narayan",
  "Sonu Nigam",
  "Shaan",
  "Sunidhi Chauhan",
  "Shreya Ghoshal",
  "Atif Aslam",
  "Rahat Fateh Ali Khan",
  "Ali Zafar",
  "Shafqat Amanat Ali",
  "Javed Ali",
  "Mohit Chauhan",
  "Himesh Reshammiya",
  "Mika Singh",
  "Daler Mehndi",
  "Honey Singh",
  "Badshah",
  "Raftaar",
  "Divine",
  "Emiway Bantai",
  "Kr$na",
  "Seedhe Maut",
  "Prabh Deep",
  "Naezy",
  "Brodha V",
  "MC Stan",
  "King",
  "Dino James",
  "Fotty Seven",
  "Bali",
  "Hanumankind",
  "Paradox",
  "MC Square",
  "Srushti Tawade",
  "Krsna",
  "Yashraj",
  "Chaahat Khanna",
  "Mintu Haryanvi",
  "Gulzaar Chhaniwala",
  "Anupam Roy",
  "Sahana Bajpaie",
  "Shayan Chowdhury Arnob",
  "Lopamudra Mitra",
  "Srikanto Acharya",
  "Nachiketa Chakraborty",
  "Kabir Suman",
  "Anjan Dutt",
  "Rupam Islam",
  "James",
  "Ayub Bachchu",
  "Andrew Kishore",
  "Sabina Yasmin",
  "Runa Laila",
  "Somlata Acharyya",
  "Iman Chakraborty",
  "Lagnajita Chakraborty",
  "Anirudh Ravichander",
  "Sid Sriram",
  "Chinmayi Sripada",
  "Jonny Greenwood",
  "Thom Yorke",
  "George Ezra",
  "Lewis Capaldi",
  "James Arthur",
  "Calum Scott",
  "Tom Odell",
  "George Michael",
  "Annie Lennox",
  "Phil Collins",
  "Sting",
  "Peter Gabriel",
  "Kate Bush",
  "Liam Gallagher",
  "Noel Gallagher",
  "Richard Ashcroft",
  "Damon Albarn",
  "Jarvis Cocker",
  "Morrissey",
  "Johnny Marr",
  "Ian Curtis",
  "Robert Smith",
  "Siouxsie Sioux",
  "Elizabeth Fraser",
  "Sinead O'Connor",
  "Dolores O'Riordan",
  "Enya",
  "Björk",
  "Sigur Rós",
  "Aurora",
  "Sigrid",
  "MØ",
  "Lykke Li",
  "Robyn",
  "Tove Lo",
  "Zedd",
  "Avicii",
  "Kygo",
  "Alan Walker",
  "Calvin Harris",
  "David Guetta",
  "Tiësto",
  "Marshmello",
  "Martin Garrix",
  "Skrillex",
  "Diplo",
  "Fred again..",
  "Four Tet",
  "Jamie xx",
  "Burial",
  "Aphex Twin",
  "Flying Lotus",
  "Kamasi Washington",
  "Jon Batiste",
  "Gregory Porter",
  "Norah Jones",
  "Diana Krall",
  "Michael Bublé",
  "Amy Winehouse",
  "Joss Stone",
  "Duffy",
  "Paloma Faith",
  "Emeli Sandé",
  "Jess Glynne",
  "Rita Ora",
  "Ellie Goulding",
  "Charli XCX",
  "FKA Twigs",
  "Rina Sawayama",
  "PinkPantheress",
  "Shygirl",
  "Eartheater",
  "Caroline Polachek",
  "Weyes Blood",
  "Angel Olsen",
  "Sharon Van Etten",
  "Mitski",
  "Japanese Breakfast",
  "Lucy Dacus",
  "Julien Baker",
  "Phoebe Bridgers",
  "Clairo",
  "Beabadoobee",
  "Arlo Parks",
  "Girl in Red",
  "King Princess",
  "MUNA",
  "The Japanese House",
  "Soccer Mommy",
  "Snail Mail",
  "Jay-Z",
  "Nas",
  "The Notorious B.I.G.",
  "Tupac Shakur",
  "Snoop Dogg",
  "Dr. Dre",
  "Ice Cube",
  "Eazy-E",
  "Rakim",
  "Big Daddy Kane",
  "Andre 3000",
  "Big Boi",
  "Lauryn Hill",
  "Missy Elliott",
  "Queen Latifah",
  "Lil Wayne",
  "Kanye West",
  "Kendrick Lamar",
  "J. Cole",
  "Travis Scott",
  "Future",
  "Young Thug",
  "Lil Uzi Vert",
  "Playboi Carti",
  "21 Savage",
  "Megan Thee Stallion",
  "Cardi B",
  "Nicki Minaj",
  "Ice Spice",
  "GloRilla",
  "Central Cee",
  "Dave",
  "Stormzy",
  "Skepta",
  "Little Simz",
  "Loyle Carner",
  "Arlo Parks",
  "Joy Crookes",
  "Celeste",
  "Mahalia",
  "Jorja Smith",
  "Kali Uchis",
  "SZA",
  "Summer Walker",
  "Kehlani",
  "Jhené Aiko",
  "Teyana Taylor",
  "H.E.R.",
  "Victoria Monét",
  "Coco Jones",
  "Brent Faiyaz",
  "Giveon",
  "Lucky Daye",
  "SiR",
  "Daniel Caesar",
  "Steve Lacy",
  "Omar Apollo",
  "Frank Ocean",
  "Miguel",
  "Solange",
  "Janelle Monáe",
  "Erykah Badu",
  "Jill Scott",
  "D'Angelo",
  "Maxwell",
  "Sade",
  "Seal",
  "Lenny Kravitz",
  "Ben Harper",
  "Jack Johnson",
  "Jason Mraz",
  "John Mayer",
  "James Bay",
  "Vance Joy",
  "Hozier",
  "George Ezra",
  "Rag'n'Bone Man",
  "Sam Fender",
  "Holly Humberstone",
  "Griff",
  "Cat Burns",
  "Flowerovlove",
  "Laufey",
  "Eloise",
  "Bruno Major",
  "Jacob Collier",
  "Madison Beer",
  "Sabrina Carpenter",
  "Tate McRae",
  "Gracie Abrams",
  "Renee Rapp",
  "Nessa Barrett",
  "Mimi Webb",
  "Lauren Spencer Smith",
  "Gayle",
  "Benson Boone",
  "Stephen Sanchez",
  "Teddy Swims",
  "Noah Kahan",
  "Zach Bryan",
  "Tyler Childers",
  "Kacey Musgraves",
  "Chris Stapleton",
  "Luke Combs",
  "Morgan Wallen",
  "Lainey Wilson",
  "Maren Morris",
  "Miranda Lambert",
  "Carrie Underwood",
  "Kelly Clarkson",
  "P!nk",
  "Avril Lavigne",
  "Hayley Williams",
  "Amy Lee",
  "Florence Welch",
  "Marina Diamandis",
  "Lana Del Rey",
  "Lorde",
  "Sky Ferreira",
  "Halsey",
  "Troye Sivan",
  "Lauv",
  "Jeremy Zucker",
  "Conan Gray",
  "Wallows",
  "The 1975",
  "Arctic Monkeys",
  "Tame Impala",
  "Glass Animals",
  "Foster The People",
  "Cage The Elephant",
  "The Black Keys",
  "The White Stripes",
  "The Killers",
  "Kings of Leon",
  "Imagine Dragons",
  "OneRepublic",
  "Coldplay",
  "Snow Patrol",
  "The Script",
  "Bastille",
  "The Lumineers",
  "Mumford & Sons",
  "Of Monsters and Men",
  "Fleet Foxes",
  "Bon Iver",
  "Sufjan Stevens",
  "Iron & Wine",
  "Elliott Smith",
  "Nick Drake",
  "Jeff Buckley",
  "Father John Misty",
  "Mac DeMarco",
  "Thundercat",
  "Flying Lotus",
  "Kamasi Washington",
  "Robert Glasper",
  "Esperanza Spalding",
  "Yussef Dayes",
  "Tom Misch",
  "Jordan Rakei",
  "Moonchild",
  "Hiatus Kaiyote",
  "Khruangbin",
  "Texas",
  "The Cardigans",
  "The Cranberries",
  "The Corrs",
  "Enya",
  "Sinead O'Connor",
  "Van Morrison",
  "U2",
  "The Pogues",
  "Thin Lizzy",
  "Rory Gallagher",
  "Chet Baker",
  "Billie Holiday",
  "Ella Fitzgerald",
  "Nina Simone",
  "Nat King Cole",
  "Sam Cooke",
  "Otis Redding",
  "Ray Charles",
  "Marvin Gaye",
  "Al Green",
  "Bill Withers",
  "Curtis Mayfield",
  "Isaac Hayes",
  "Barry White",
  "Luther Vandross",
  "George Benson",
  "Lionel Richie",
  "Chaka Khan",
  "Donna Summer",
  "Gloria Gaynor",
  "Diana Ross",
  "Tina Turner",
  "Cher",
  "Barbra Streisand",
  "Bette Midler",
  "Dolly Parton",
  "Kenny Rogers",
  "Willie Nelson",
  "Johnny Cash",
  "Waylon Jennings",
  "Kris Kristofferson",
  "Townes Van Zandt",
  "Lucinda Williams",
  "Emmylou Harris",
  "Gram Parsons",
  "Grateful Dead",
  "Phish",
  "Dave Matthews",
  "John Butler",
  "Xavier Rudd",
  "Ziggy Marley",
  "Damian Marley",
  "Stephen Marley",
  "Buju Banton",
  "Sizzla",
  "Beenie Man",
  "Sean Paul",
  "Shaggy",
  "Koffee",
  "Chronixx",
  "Protoje",
  "Lila Iké",
  "Tyla",
  "Ayra Starr",
  "Burna Boy",
  "Wizkid",
  "Davido",
  "Tems",
  "Olamide",
  "Asake",
  "Fireboy DML",
  "Rema",
  "Ckay",
  "Joeboy",
  "Tiwa Savage",
  "Santi",
  "Amaarae",
  "Odunsi",
  "Lady Donli",
  "Sautisol",
  "Black Coffee",
  "Master KG",
  "Niniola",
  "Fela Kuti",
  "Tony Allen",
  "Miriam Makeba",
  "Hugh Masekela",
  "Brenda Fassie",
  "Ali Farka Touré",
  "Oumou Sangaré",
  "Salif Keita",
  "Angelique Kidjo",
  "Youssou N'Dour",
  "Baaba Maal",
  "Tinariwen",
  "Narayan Gopal",
  "Aruna Lama",
  "Tara Devi",
  "Prem Dhoj Pradhan",
  "Bhakta Raj Acharya",
  "Amber Gurung",
  "Gopal Yonjan",
  "Phatteman",
  "Deepak Kharel",
  "Om Bikram Bista",
  "Sugam Pokharel",
  "Nabin K Bhattarai",
  "Adrian Pradhan",
  "Phiroj Shyangden",
  "Karna Das",
  "Ram Krishna Dhakal",
  "Anju Panta",
  "Pramod Kharel",
  "Milan Newar",
  "Shiva Pariyar",
  "Rajesh Payal Rai",
  "Swarup Raj Acharya",
  "Sajjan Raj Vaidya",
  "Sushant KC",
  "Bartika Eam Rai",
  "Oasis Thapa",
  "Yugal Gurung",
  "Trishala Gurung",
  "Wangden Sherpa",
  "Uniq Poet",
  "Yama Buddha",
  "Vten",
  "Sacar",
  "Dong",
  "Laure",
  "Professor Trix",
  "Ashish Rana",
  "B-832",
  "Albatross",
  "Nepathya",
  "1974 AD",
  "Robin Tamang",
  "Abhaya Subba",
  "Cobweb",
  "Edge Band",
  "Shadows Nepal",
  "Monkey Temple",
  "Night",
  "Kutumba",
  "Pahenlo Batti Muni",
  "Phosphenes",
  "Gauley Bhai",
  "Bipul Chettri",
  "Arthur Gunn",
  "Jeromes",
  "Prajina",
  "Vek",
  "Neetesh Jung Kunwar",
  "John and the Locals",
  "Tribal Rain",
  "Anupa",
  "Kritika",
  "Subani Moktan",
  "Aasish Gurung",
  "Manish Dhakal",
  "Jitesh Rai",
  "The Elements",
  "Ulto Pulto",
  "Space",
  "Asmita Adhikari",
  "Melina Rai",
  "Eleena Chauhan",
  "Nitesh Jung Kunwar",
  "Swapnil Sharma",
  "Bivek Singh",
  "Manna Dey",
  "Hemanta Mukherjee",
  "Kishore Kumar",
  "Shyamal Mitra",
  "Satinath Mukhopadhyay",
  "Sandhya Mukhopadhyay",
  "Arati Mukhopadhyay",
  "Pratima Bandopadhyay",
  "Hoimanti Shukla",
  "Indranil Sen",
  "Srikanto Acharya",
  "Lopamudra Mitra",
  "Nachiketa Chakraborty",
  "Kabir Suman",
  "Anjan Dutt",
  "Rupam Islam",
  "Anupam Roy",
  "Sahana Bajpaie",
  "Shayan Chowdhury Arnob",
  "Tanzir Tuhin",
  "Lincoln",
  "Sunjoy",
  "Andrew Kishore",
  "Sabina Yasmin",
  "Runa Laila",
  "Somlata Acharyya",
  "Rupankar Bagchi",
  "Iman Chakraborty",
  "Lagnajita Chakraborty",
  "Silajit Majumder",
  "Siddhartha Sankar Ray",
  "Joy Sarkar",
  "Raghab Chattopadhyay",
  "Srabori Sen",
  "Jayati Chakraborty",
  "Aditi Munshi",
  "Sasha Ghoshal",
  "Durnibar Saha",
  "Mekhla Dasgupta",
  "Animesh Roy",
  "Ali Sethi",
  "Zeb Bangash",
  "Hania Aslam",
  "Meesha Shafi",
  "Shafqat Amanat Ali",
  "Sajjad Ali",
  "Ali Zafar",
  "Atif Aslam",
  "Bilal Saeed",
  "Momina Mustehsan",
  "Quratulain Balouch",
  "Aima Baig",
  "Sahir Ali Bagga",
  "Nabeel Shaukat Ali",
  "Zoe Viccaji",
  "Young Stunners",
  "Talha Anjum",
  "Talha Yunus",
  "Farhan Saeed",
  "Asim Azhar",
  "Abdul Hannan",
  "Hasan Raheem",
  "Kaifi Khalil",
  "Taha G",
  "Maanu",
  "Natasha Noorani",
  "Shubh",
  "AP Dhillon",
  "Gurinder Gill",
  "Sidhu Moose Wala",
  "Karan Aujla",
  "Diljit Dosanjh",
  "Amrit Maan",
  "Sharry Maan",
  "Gippy Grewal",
  "Babbu Maan",
  "Satinder Sartaaj",
  "Amrinder Gill",
  "Kulwinder Billa",
  "Shivjot",
  "Gurnam Bhullar",
  "Jordan Sandhu",
  "Mankirt Aulakh",
  "Parmish Verma",
  "Taz Stereo Nation",
  "Apache Indian",
  "Bally Sagoo",
  "Panjabi MC",
  "Jay Sean",
  "Rishi Rich",
  "Juggy D",
  "Raghav",
  "Dr Zeus",
  "Zack Knight",
  "Mickey Singh",
  "Arjun",
  "Vidya Vox",
  "Shirley Setia",
  "Penn Masala",
  "The Yellow Diary",
  "Prateek Kuhad",
  "Anuv Jain",
  "The Local Train",
  "Parekh & Singh",
  "When Chai Met Toast",
  "Taba Chake",
  "Osho Jain",
  "Aditya Rikhari",
  "Raman Negi",
  "Seedhe Maut",
  "Prabh Deep",
  "Kr$na",
  "Raftaar",
  "Badshah",
  "Honey Singh",
  "Divine",
  "Brodha V",
  "Naezy",
  "MC Stan",
  "King",
  "Dino James",
  "Fotty Seven",
  "Bali",
  "Hanumankind",
  "Paradox",
  "MC Square",
  "Srushti Tawade",
  "Yashraj",
  "Chaahat Khanna",
  "Mintu Haryanvi",
];
